config/routes.rb
Blog::Application.routes.draw do
  get "welcome/index"

       resources :articles

   root :to => 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	include ActiveModel::ForbiddenAttributesProtection
 	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  attr_accessible :body, :commenter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def new 
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	#New
	def new 
		@article = Article.new
	end

	#Create
	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
		#render plain: params[:article].inspect
	end

	#Show
  	def show
  		@article = Article.find(params[:id])
  	end

  	#Index
  	def index
  		@articles = Article.all
  	end

  	#Edit
  	def edit
	  @article = Article.find(params[:id])
	end

	#Update
	def update
	  @article = Article.find(params[:id])
	 
	  if @article.update(article_params)
	    redirect_to @article
	  else
	    render 'edit'
	  end
	end

	#Destroy
	def destroy
	  @article = Article.find(params[:id])
	  @article.destroy
	 
	  redirect_to articles_path
	end

  	private
  		def article_params
    		params.require(:article).permit(:title, :text)
  		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit class: 'btn show' %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<div class="center">
  <h1>Edit article</h1>
  <%= render 'form' %> 
  <%= link_to 'Back', articles_path, class: 'btn destroy' %>
</div>

app/views/articles/index.html.erb
<div class="center">
  <h1>Listing articles</h1>
  <%= link_to 'New article', new_article_path, class: 'btn new' %>
  <table>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="2"></th>
    </tr>
   
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article), class: 'btn show' %></td>
      <td><%= link_to 'Edit', edit_article_path(article), class: 'btn edit' %></td>
      <td><%= link_to 'Destroy', article_path(article),class: 'btn destroy',
                      method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/articles/new.html.erb
<div class="center">
	<h1>New article</h1>
	<%= render 'form' %>
	<%= link_to 'Back', articles_path, class: 'btn destroy' %>
</div>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Back', articles_path %> | <%= link_to 'Edit', edit_article_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello Rails!  By Villanuevand</h1>
<%= link_to 'My Blog', controller: 'articles'%>